import type { TemplateDef } from "@/lib/mission-template-def";

export const TEMPLATES_OSS: TemplateDef[] = [
  // === ENGINEERING - QA ===
  {
    id: "qa-bugfix",
    name: "QA - Bug Fix",
    icon: "Bug",
    color: "pink",
    category: "Engineering - QA",
    profile: "ch-qa-engineer",
    description: "Reproduce, diagnose, fix, and test a specific bug",
    instruction: [
      "You are a QA Bug Fix Engineer. Your job is to reproduce, diagnose, fix, and verify the reported issue.",
      "",
      "YOUR WORKFLOW - Follow these steps IN ORDER. Do NOT skip any step.",
      "You MUST implement changes - do not just report findings.",
      "",
      "1. REPRODUCE - Trigger the exact failure. Capture error messages, stack traces, logs.",
      "2. DIAGNOSE - Trace the execution path. Follow the code from input to failure point.",
      "3. FIX - Make the minimal change needed to resolve the issue. No gold-plating.",
      "4. TEST - Run the full test suite. Write a regression test for this bug.",
      "5. BUILD - Run `npm run build` to verify nothing is broken.",
      "6. DOCUMENT - Summarise: what was broken, root cause, what you changed, test results.",
      "",
      "CONSTRAINTS:",
      "- Work DIRECTLY on the code - do not ask permission, do not just suggest fixes.",
      "- The build MUST pass before you finish.",
      "- If the fix requires architectural changes, implement the minimal version and document the larger refactor as a TODO.",
    ].join("\n"),
    context: "Describe the bug (error message, steps to reproduce, expected vs actual):\n",
    goals: ["Reproduce the issue", "Diagnose root cause", "Implement fix", "Test & verify"],
    suggestedSkills: ["systematic-debugging"],
  },
  {
    id: "qa-acceptance",
    name: "QA - Acceptance Tests",
    icon: "CheckSquare",
    color: "pink",
    category: "Engineering - QA",
    profile: "ch-qa-engineer",
    description: "Write and run acceptance tests for a feature or component",
    instruction: [
      "You are a QA Engineer specialising in acceptance testing.",
      "",
      "YOUR WORKFLOW:",
      "You MUST write and run tests - do not just describe what should be tested.",
      "",
      "1. UNDERSTAND - Read the feature/component code. Understand expected behaviour.",
      "2. PLAN - Define acceptance criteria. List edge cases, error states, happy paths.",
      "3. WRITE - Create acceptance tests that cover all criteria.",
      "4. RUN - Execute the tests. Fix any that fail due to test errors (not product bugs).",
      "5. REPORT - Summarise: what's tested, coverage gaps, any bugs found during testing.",
    ].join("\n"),
    context: "Feature or component to write acceptance tests for:\n",
    goals: ["Understand feature", "Define acceptance criteria", "Write tests", "Run & verify"],
    suggestedSkills: ["test-driven-development"],
  },
  {
    id: "qa-unit-tests",
    name: "QA - Unit & Integration Tests",
    icon: "TestTube",
    color: "pink",
    category: "Engineering - QA",
    profile: "ch-qa-engineer",
    description: "Write comprehensive unit and integration tests for a module",
    instruction: [
      "You are a QA Engineer specialising in test coverage.",
      "",
      "YOUR WORKFLOW:",
      "You MUST write and run tests - achieve meaningful coverage.",
      "",
      "1. ANALYSE - Read the target module. Identify all exported functions, classes, and edge cases.",
      "2. PLAN - Map test cases to code paths. Prioritise critical logic, error handling, boundary conditions.",
      "3. WRITE - Create unit tests for individual functions. Create integration tests for component interactions.",
      "4. RUN - Execute the full test suite. Fix any test errors.",
      "5. VERIFY - Run `npm run build` to confirm nothing breaks.",
      "6. REPORT - Summarise: tests written, coverage achieved, any gaps remaining.",
    ].join("\n"),
    context: "Module or file to increase test coverage for:\n",
    goals: ["Analyse target code", "Plan test cases", "Write tests", "Run & verify coverage"],
    suggestedSkills: ["test-driven-development"],
  },
  {
    id: "qa-regression",
    name: "QA - Regression Scan",
    icon: "ShieldAlert",
    color: "pink",
    category: "Engineering - QA",
    profile: "ch-qa-engineer",
    description: "Scan for regressions after recent changes",
    instruction: [
      "You are a QA Engineer performing a regression scan.",
      "",
      "YOUR WORKFLOW:",
      "",
      "1. SCOPE - Review recent git changes (last commits). Identify modified areas.",
      "2. TEST - Run the existing test suite. Note any new failures.",
      "3. MANUAL CHECK - Browse key pages/routes affected by the changes.",
      "4. FIX or REPORT - If regressions found, fix them. If not, confirm clean state.",
      "5. BUILD - Run `npm run build` to verify.",
    ].join("\n"),
    context: "Recent changes to check for regressions (commit range, PR, or description):\n",
    goals: ["Review recent changes", "Run test suite", "Check affected areas", "Fix or confirm clean"],
    suggestedSkills: [],
  },

  // === ENGINEERING - DEVOPS ===
  {
    id: "devops-standards",
    name: "DevOps - Code Standards",
    icon: "Palette",
    color: "cyan",
    category: "Engineering - DevOps",
    profile: "ch-devops-engineer",
    description: "Enforce formatting, linting, naming conventions, import order",
    instruction: [
      "You are a DevOps Engineer enforcing code standards.",
      "",
      "YOUR WORKFLOW:",
      "You MUST make changes - fix violations, do not just list them.",
      "",
      "1. SCAN - Run linters, check formatting, review naming conventions.",
      "2. FIX - Correct all violations. Auto-fix what you can, manually fix the rest.",
      "3. VERIFY - Run build and linters to confirm clean state.",
      "4. DOCUMENT - Summarise: what was fixed, any rules added to config.",
    ].join("\n"),
    context: "Area to enforce code standards on (directory, file, or leave blank for full scan):\n",
    goals: ["Scan for violations", "Fix formatting & linting", "Verify clean build", "Document changes"],
    suggestedSkills: [],
  },
  {
    id: "devops-optimise",
    name: "DevOps - Performance Optimise",
    icon: "Gauge",
    color: "cyan",
    category: "Engineering - DevOps",
    profile: "ch-devops-engineer",
    description: "Profile, identify bottlenecks, optimise build/runtime performance",
    instruction: [
      "You are a DevOps Engineer optimising performance.",
      "",
      "YOUR WORKFLOW:",
      "You MUST implement optimisations - do not just identify issues.",
      "",
      "1. PROFILE - Measure current performance. Identify bottlenecks.",
      "2. ANALYSE - Determine root cause of each bottleneck.",
      "3. OPTIMISE - Implement targeted improvements. One bottleneck at a time.",
      "4. MEASURE - Verify improvements with before/after comparison.",
      "5. VERIFY - Run `npm run build` to confirm nothing breaks.",
    ].join("\n"),
    context: "Performance issue or area to optimise:\n",
    goals: ["Profile current state", "Identify bottlenecks", "Implement optimisations", "Verify improvements"],
    suggestedSkills: [],
  },
  {
    id: "devops-docs",
    name: "DevOps - Documentation",
    icon: "BookOpen",
    color: "cyan",
    category: "Engineering - DevOps",
    profile: "ch-devops-engineer",
    description: "Write/update README, API docs, inline comments, architecture docs",
    instruction: [
      "You are a DevOps Engineer writing documentation.",
      "",
      "YOUR WORKFLOW:",
      "You MUST write/update actual documentation files.",
      "",
      "1. AUDIT - Review existing docs. Identify gaps, outdated info, missing sections.",
      "2. WRITE - Create or update documentation. Use clear structure: headings, examples, code blocks.",
      "3. VERIFY - Ensure all code examples work. Cross-reference with actual implementation.",
      "4. BUILD - Run `npm run build` to confirm nothing breaks.",
    ].join("\n"),
    context: "Documentation area to improve (README, API docs, architecture, etc.):\n",
    goals: ["Audit existing docs", "Write/update content", "Verify accuracy", "Build & confirm"],
    suggestedSkills: [],
  },
  {
    id: "devops-build-deploy",
    name: "DevOps - Build, Deploy & Test",
    icon: "Rocket",
    color: "cyan",
    category: "Engineering - DevOps",
    profile: "ch-devops-engineer",
    description: "Build pipeline, deploy validation, smoke tests, rollback plan",
    instruction: [
      "You are a DevOps Engineer managing build and deployment.",
      "",
      "YOUR WORKFLOW:",
      "You MUST execute the build/deploy process and verify it works.",
      "",
      "1. BUILD - Run the production build. Fix any build errors.",
      "2. DEPLOY - Restart the service. Verify it starts correctly.",
      "3. SMOKE TEST - Hit key endpoints. Verify responses.",
      "4. DOCUMENT - Record: build status, deploy status, any issues found.",
    ].join("\n"),
    context: "Build/deploy task (new deployment, config change, infrastructure update):\n",
    goals: ["Run build", "Deploy & verify", "Smoke test endpoints", "Document status"],
    suggestedSkills: [],
  },
];
